### ISSUE TITLE
OAuth for Github - Feature migrated from NodeJS API

### ISSUE THREAD

**Issue by app-generator** [app-generator/api-server-django#11]
The goal of this task is to update this codebase in order to support OAuth for Github, in the same way as this NodeJS API: 

- https://github.com/app-generator/api-server-nodejs
  - The commits that add the feature to the NodeJS codebase are highlighted below: 

![image](https://user-images.githubusercontent.com/51070104/205666790-7470217b-8af6-4445-8dd7-bbf468f1ef0e.png)

### For a complete set up:

- Create a new GitHub OAuth app using `https://localhost:3000` as the callback URL
- Start the NodeJS API 
  -   port `5000` (default) 
  - Save in `.env` the Github Secrets
- Start the React UI
  - https://github.com/app-generator/react-soft-ui-dashboard
  - use HTTPS
  - save in `.env` the GitHub Secrets
  - start the app

Go to the login page & use the GH Authentication. 

All should work 

For more information, I'm here.

**Comment by app-generator** [comment]
Hello @mominur-helios 
In the latest version the request fails when the user is created. 

Not in all cases, the user information pulled from the OAuth provider have email. 
We need to make email optional in DB. 

Please take a look. Ty! 

Here is the latest runtime error:

```log
[07/Dec/2022 15:29:10] "GET /api/sessions/oauth/github?code=e394948fd3ecf338971f HTTP/1.1" 301 0
Internal Server Error: /api/sessions/oauth/github/
Traceback (most recent call last):
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\work\repo-boilerplates\api-server-django\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\repo-boilerplates\api-server-django\api\authentication\viewsets\social_login.py", line 39, in get
    user = User.objects.create_user(username=user_data['login'], email=user_data['email'])
  File "D:\work\repo-boilerplates\api-server-django\api\user\models.py", line 16, in create_user
    raise TypeError("Users must have an email.")
TypeError: Users must have an email.
[07/Dec/2022 15:29:11] "GET /api/sessions/oauth/github/?code=e394948fd3ecf338971f HTTP/1.1" 500 103015
```

**Comment by app-generator** [comment]
Validated. Closing. 
Ty @mominur-helios & @MySecondLanguage 
Great work
